In [11]:
import pandas as pd

In [12]:
df = pd.read_excel('data/raw/Z06_dane_proj2.xls')
df.head()

,status kredytobiorcy,status mieszkania,Dochód I-go kredytob..,Dochód II-go kredytob./żyranta,miejsce zam,poziom wykształcenia I-go,rodzaj wyksztalcenia I-go,wiek I-go kredytob.,staż pracy I-go kredytob.,Aktyw/pasywa I-go kredytobiorcy,...,posiada ROR,posiada debetową ?,Czy korzysta z dostepu do produktów przez intrernet?,Czy ma konto na facebooku,czy ktos z Jego znajomych na facebooku jest w rejestrze ndłuzników?,ile posiada produktów w Naszym banku?,w ilu bankach ma zakupioneprodukty ?,liczba aktualnieposiadanych kredytów,czy był w tym roku na wakacjach zagranicznych?,czy z konta na Facebooku wynika że lubi piwo?
0,Y,X1,X2,X3,X4,X5,X6,X7,X8,X9,...,X17,X18,X19,X20,X21,X22,X23,X24,X25,X26
1,0,mieszk. wynajemm,8248.47,3119.35,małe m.,licencjat,biologiczne,62,43,94486.88,...,tak,tak,nie,tak,tak,1,1,1,nie,tak
2,0,mieszk. wł.,10134.22,8155.38,osiedle,mgr,techniczne,45,28,21172.64,...,nie,nie,tak,tak,nie,2,1,1,nie,nie
3,0,mieszk. wynajemm,10439.73,6974.29,duże m.,mgr,biologiczne,54,34,25393.72,...,nie,tak,tak,nie,nie,2,1,1,nie,nie
4,0,mieszk. wł.,8504.42,4570.26,średnie m.,licencjat,techniczne,67,51,34875.15,...,tak,nie,tak,tak,tak,2,1,1,nie,nie

In [13]:
df.describe()

,status kredytobiorcy,status mieszkania,Dochód I-go kredytob..,Dochód II-go kredytob./żyranta,miejsce zam,poziom wykształcenia I-go,rodzaj wyksztalcenia I-go,wiek I-go kredytob.,staż pracy I-go kredytob.,Aktyw/pasywa I-go kredytobiorcy,...,posiada ROR,posiada debetową ?,Czy korzysta z dostepu do produktów przez intrernet?,Czy ma konto na facebooku,czy ktos z Jego znajomych na facebooku jest w rejestrze ndłuzników?,ile posiada produktów w Naszym banku?,w ilu bankach ma zakupioneprodukty ?,liczba aktualnieposiadanych kredytów,czy był w tym roku na wakacjach zagranicznych?,czy z konta na Facebooku wynika że lubi piwo?
count,2401,2401,2401.00,2401.00,2401,2401,2401,2401,2401,2401.00,...,2401,2401,2401,2401,2401,2401,2401,2002,2002,2002
unique,3,6,1199.00,1200.00,5,6,8,51,53,1201.00,...,3,3,3,3,3,6,6,6,3,3
top,0,mieszk. wł.,7240.44,4251.44,duże m.,średnie,ogolne,45,22,15090.88,...,tak,tak,tak,tak,nie,1,1,1,nie,nie
freq,1200,824,4.00,4.00,734,1010,660,94,104,2.00,...,1204,1278,1575,1226,1444,806,1868,1702,1008,1196

In [14]:
one_hot = pd.get_dummies(df['status mieszkania'], prefix='status mieszkania')
df = pd.concat([df, one_hot], axis=1)
# df = df.drop('status mieszkania', axis=1)

In [ ]:
df[['status mieszkania', 'status mieszkania_X1',
       'status mieszkania_dom', 'status mieszkania_dom wynajem',
       'status mieszkania_mieszk. wynajemm', 'status mieszkania_mieszk. wł.',
       'status mieszkania_socjalne']]

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[2401 rows x 0 columns]

In [15]:
df.columns

Index(['status kredytobiorcy', 'status mieszkania', 'Dochód I-go kredytob..',
       'Dochód II-go kredytob./żyranta', 'miejsce zam',
       'poziom wykształcenia I-go', 'rodzaj wyksztalcenia I-go',
       'wiek I-go kredytob.', 'staż pracy I-go kredytob.',
       'Aktyw/pasywa I-go kredytobiorcy', 'rodzaj zatrudnienia',
       'miejsce urodzenia I-szego', 'stan rodzinny', 'Wartość samoch.',
       'rodzaj pracodawcy', 'wielkość pracodawcy', 'posiada kartę kredytową ?',
       'posiada  ROR', 'posiada debetową ?',
       'Czy korzysta z dostepu do produktów przez intrernet?',
       'Czy ma konto na facebooku',
       'czy ktos z Jego znajomych na facebooku jest w rejestrze ndłuzników?',
       'ile posiada produktów w Naszym banku?',
       'w ilu bankach ma zakupioneprodukty ?',
       'liczba aktualnieposiadanych kredytów',
       'czy był w tym roku na wakacjach zagranicznych?',
       'czy z konta na Facebooku wynika że lubi piwo?', 'status mieszkania_X1',
       'status mieszkania_dom', 'status mieszkania_dom wynajem',
       'status mieszkania_mieszk. wynajemm', 'status mieszkania_mieszk. wł.',
       'status mieszkania_socjalne'],
      dtype='object')